# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'Image-Build'
    targetPath: '$(Pipeline.Workspace)/target/*.jar'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Pipeline.Workspace)/target'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Image-Build.zip'
    
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'Image-Build'
    artifactPath: '$(Build.ArtifactStagingDirectory)/Image-Build.zip'
